### ISSUE TITLE
Uncaught TypeError: Cannot read property 'expand' of undefined

### ISSUE THREAD

**Issue by code4ape** [mantrajs/mantrajs-atom-package#23] opened 2016-04-19 02:05 UTC
[Enter steps to reproduce below:]
1. active MantraPanel
2. double click any thing on the Panel.

**Atom Version**: 1.7.2
**System**: Mac OS X 10.10.4
**Thrown From**: [mantrajs](https://github.com/tomitrescak/mantrajs-atom-package) package, v0.3.0
### Stack Trace

Uncaught TypeError: Cannot read property 'expand' of undefined

```
At /Users/myu/.atom/packages/mantrajs/lib/directoryHandler.coffee:82

TypeError: Cannot read property 'expand' of undefined
    at Function.module.exports.DirectoryHandler.revealActiveFile (/Users/myu/.atom/packages/mantrajs/lib/directoryHandler.coffee:82:15)
    at HTMLLIElement.<anonymous> (/Users/myu/.atom/packages/mantrajs/lib/directoryHandler.coffee:50:24)
    at HTMLOListElement.jQuery.event.dispatch (/Users/myu/.atom/packages/mantrajs/node_modules/space-pen/vendor/jquery.js:4681:9)
    at HTMLOListElement.elemData.handle (/Users/myu/.atom/packages/mantrajs/node_modules/space-pen/vendor/jquery.js:4359:28)
```
### Commands

```
     -5:04.1.0 mantrajs:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
mantrajs, v0.3.0
meteor-api, v2.20.0
minimap, v4.22.1
pigments, v0.26.0
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by macrozone** [comment] 2016-06-08 12:35
duplicate of https://github.com/mantrajs/mantrajs-atom-package/issues/27

**Closed as completed** 2016-06-16 00:44 UTC
